run:
  timeout: 5m
  tests: false

linters:
  enable:
    - deadcode       # func/var/type never used
    - unused         # import/var never used
    - ineffassign
    - gosimple
    - staticcheck
    - typecheck
    - errcheck
    - govet
    - gocritic

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
